all:
  children:
    srl_nodes:
      hosts:
        spine1:
          ansible_host: 172.20.20.10
        spine2:
          ansible_host: 172.20.20.20
        leaf1:
          ansible_host: 172.20.20.30
        leaf2:
          ansible_host: 172.20.20.40

      vars:
        ansible_user: admin
        ansible_password: NokiaSrl1!
        ansible_connection: httpapi
        ansible_network_os: nokia.srlinux.srlinux
