---
- name: change_hostname
  hosts: srl_nodes
  gather_facts: false

  tasks:
    - name: change host name
      nokia.srlinux.config:
        update:
          - path: "/system/name/host-name"
            value: "{{ inventory_hostname }}"